### ISSUE TITLE
Unexpected SSAT test results

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/meta-neural-network#54]
In qemu (BusyBox),

The `callCompareTest` of files which do not exist returns PASS.
When the file does not exist, in BusyBox condition, the bufsize is null and results of `dd` are same error message. And unexpected PASS result follows.

**Comment by myungjoo** [comment]
Update the status. Close if it's fixed with SSAT#15

**Comment by anyj0527** [comment]
Closed via https://github.com/myungjoo/SSAT/pull/15
