### ISSUE TITLE
NNtrainer yocto-build.patch file "0001-Patch-for-yocto-build.patch" not upgraded with latest meson.build file in nntrainer repo

### ISSUE THREAD

**Issue by ptrivedi2610** [nnstreamer/meta-neural-network#67]
Hi,

We tried to build the meta-neural-network layer for nnstreamer. While building, we observed that the patch files for yocto build are not up-to-date with the latest meson.build files (example yocto build file for nntrainer).

Because of this, we receive errors during the build. PFA for the txt file indicating the errors.

Can you please provide the updated files, so that the patch can be directly applied to the build ? 
[build_failed.txt](https://github.com/nnstreamer/meta-neural-network/files/6877366/build_failed.txt)

**Comment by myungjoo** [comment]
@anyj0527 / @lhs8928 : Please update https://github.com/nnstreamer/meta-neural-network/blob/master/recipes-nntrainer/nntrainer/files/0001-Patch-for-yocto-build.patch for given https://github.com/nnstreamer/meta-neural-network/blob/master/recipes-nntrainer/nntrainer/nntrainer_0.1.1.bb

Or (@lhs8928) can you update nntrainer.git so that this patch file is no longer required?

**Comment by myungjoo** [comment]
> @anyj0527 / @lhs8928 : Please update https://github.com/nnstreamer/meta-neural-network/blob/master/recipes-nntrainer/nntrainer/files/0001-Patch-for-yocto-build.patch for given https://github.com/nnstreamer/meta-neural-network/blob/master/recipes-nntrainer/nntrainer/nntrainer_0.1.1.bb
> 
> Or (@lhs8928) can you update nntrainer.git so that this patch file is no longer required?

Updates: @lhs8928 : Please update nntrainer.git's build script so that Yocto works without the patch. Then, remove this patch.

**Comment by anyj0527** [comment]
@ptrivedi2610 
Recently we added recipe for ml-api (https://github.com/nnstreamer/api), which is needed by nntrainer.
And fixed the recipe for nntrainer, at least to be built. Please check #75
